name: Test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    name: Rust project
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master

      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
