name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: mirua
            asset_name: mirua_linux_x86_64

          - os: windows-latest
            artifact_name: mirua.exe
            asset_name: mirua_windows_x86_64.exe

          - os: macos-latest
            artifact_name: mirua
            asset_name: mirua_macos_x86_64

    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master

      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      - name: Strip
        if: ${{ !startsWith(matrix.os, 'windows') }}
        run: strip target/release/${{ matrix.artifact_name }}

      - name: Rename
        run: mv target/release/${{ matrix.artifact_name }} target/release/${{ matrix.asset_name }}

      - name: Push file
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: target/release/${{ matrix.asset_name }}
          destination_repo: zkonge/mirua-update
          destination_folder: ${{ github.event.release.tag_name }}
          user_email: bot@konge.pw
          user_name: zkonge

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
