name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: mirua
            asset_name: mirua_linux_amd64

          - os: windows-latest
            artifact_name: mirua.exe
            asset_name: mirua_windows_amd64.exe

          - os: macos-latest
            artifact_name: mirua
            asset_name: mirua_macos_amd64

    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master

      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      - name: Strip
        if: ${{ !startsWith(matrix.os, 'windows') }}
        run: strip target/release/${{ matrix.artifact_name }}

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
